### ISSUE TITLE
Insufficient description

### ISSUE THREAD

**Issue by mudrd8mz** [lnoSlevin/block_enroleasy#1]
The block's description at https://moodle.org/plugins/block_enroleasy is really sparse. It did not even contain a link to the said enrolment method, which we had to add ourselves.

By reading the description, visitors should get know easily:

* what use-case / problem / situation this block solves
* where it should be placed on the site
* how teachers and student interact with it

etc.

**Comment by ghost** [comment]
Thank you, description was updated.
